# Generated by Django 4.2.6 on 2023-10-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delay', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('delivery_at', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('state', models.IntegerField(choices=[(0, 'Assigned'), (1, 'At Vendor'), (2, 'Picked'), (3, 'Delivered')], default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='DelayReportCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('state', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Assigned'), (2, 'Checked')], default=0)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_report_checks', to='agent.agent')),
                ('delay_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='order.delayreport')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_report_checks', to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='delayreport',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reports', to='order.order'),
        ),
    ]
