# Generated by Django 4.2.6 on 2023-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delayreportcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('state__lte', 1)), fields=('order',), name='order_delayreportcheck_unique_unchecked_order'),
        ),
    ]
