# Generated by Django 4.2.6 on 2023-10-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delayreportcheck_order_delayreportcheck_unique_unchecked_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delayreportcheck',
            options={'ordering': ['created_at']},
        ),
    ]
