# Generated by Django 4.2.6 on 2023-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_delayreportcheck_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayreport',
            name='new_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
