# Generated by Django 4.2.6 on 2023-10-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delayreport_new_delivery_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayreportcheck',
            name='delay_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay_check', to='order.delayreport'),
        ),
    ]
